// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetMachineHostname
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetMachineHostname": () => {
        return window.go.main.App.GetMachineHostname();
      },
      /**
       * GetMachineID
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetMachineID": () => {
        return window.go.main.App.GetMachineID();
      },
      /**
       * GetOS
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetOS": () => {
        return window.go.main.App.GetOS();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
    },
  },

};
export default go;
