// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetDefaultLocalIP
       * @returns {Promise<models.IP>}  - Go Type: net.IP
       */
      "GetDefaultLocalIP": () => {
        return window.go.main.App.GetDefaultLocalIP();
      },
      /**
       * GetGatewayIP
       * @returns {Promise<models.IP>}  - Go Type: net.IP
       */
      "GetGatewayIP": () => {
        return window.go.main.App.GetGatewayIP();
      },
      /**
       * GetIPNetFromIP
       * @param {models.IP} arg1 - Go Type: net.IP
       * @returns {Promise<models.IPNet>}  - Go Type: net.IPNet
       */
      "GetIPNetFromIP": (arg1) => {
        return window.go.main.App.GetIPNetFromIP(arg1);
      },
      /**
       * GetIfaceFromIP
       * @param {models.IP} arg1 - Go Type: net.IP
       * @returns {Promise<models.Interface>}  - Go Type: net.Interface
       */
      "GetIfaceFromIP": (arg1) => {
        return window.go.main.App.GetIfaceFromIP(arg1);
      },
      /**
       * GetMACFromString
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<models.HardwareAddr>}  - Go Type: net.HardwareAddr
       */
      "GetMACFromString": (arg1) => {
        return window.go.main.App.GetMACFromString(arg1);
      },
      /**
       * GetMachineHostname
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetMachineHostname": () => {
        return window.go.main.App.GetMachineHostname();
      },
      /**
       * GetMachineID
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetMachineID": () => {
        return window.go.main.App.GetMachineID();
      },
      /**
       * GetOS
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetOS": () => {
        return window.go.main.App.GetOS();
      },
      /**
       * GetVersion
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetVersion": () => {
        return window.go.main.App.GetVersion();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * Initialize
       * @param {models.Interface} arg1 - Go Type: net.Interface
       * @returns {Promise<void>} 
       */
      "Initialize": (arg1) => {
        return window.go.main.App.Initialize(arg1);
      },
      /**
       * LookupARPTable
       * @param {models.IP} arg1 - Go Type: net.IP
       * @returns {Promise<models.MACInfo>}  - Go Type: main.MACInfo
       */
      "LookupARPTable": (arg1) => {
        return window.go.main.App.LookupARPTable(arg1);
      },
      /**
       * Poison
       * @param {models.PoisonParams} arg1 - Go Type: main.PoisonParams
       * @returns {Promise<void>} 
       */
      "Poison": (arg1) => {
        return window.go.main.App.Poison(arg1);
      },
      /**
       * Quit
       * @returns {Promise<void>} 
       */
      "Quit": () => {
        return window.go.main.App.Quit();
      },
      /**
       * Scan
       * @param {models.Interface} arg1 - Go Type: net.Interface
       * @param {models.IPNet} arg2 - Go Type: net.IPNet
       * @param {number} arg3 - Go Type: int
       * @returns {Promise<void>} 
       */
      "Scan": (arg1, arg2, arg3) => {
        return window.go.main.App.Scan(arg1, arg2, arg3);
      },
      /**
       * SetJWT
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SetJWT": (arg1) => {
        return window.go.main.App.SetJWT(arg1);
      },
      /**
       * StartListening
       * @returns {Promise<void>} 
       */
      "StartListening": () => {
        return window.go.main.App.StartListening();
      },
      /**
       * StopPoison
       * @param {models.PoisonParams} arg1 - Go Type: main.PoisonParams
       * @returns {Promise<void>} 
       */
      "StopPoison": (arg1) => {
        return window.go.main.App.StopPoison(arg1);
      },
      /**
       * StopScan
       * @returns {Promise<void>} 
       */
      "StopScan": () => {
        return window.go.main.App.StopScan();
      },
      /**
       * UpdateCheck
       * @returns {Promise<void>} 
       */
      "UpdateCheck": () => {
        return window.go.main.App.UpdateCheck();
      },
    },
  },

};
export default go;
